# Generated by Django 3.0.8 on 2020-07-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='dominio2',
            field=models.CharField(max_length=30),
        ),
    ]
